### ISSUE TITLE
EPIC: WDM Resiliency

### ISSUE THREAD

**Issue by ianwremmel** [webex/webex-js-sdk#741]
- [ ] There's currently no retry on registration failure; we'll need to add an exponential backoff. The mercury connection code should provide prior art.
- [ ] If PUT fails because the registatration is no longer valid, we'll need to POST. (this can't happen yet, but they're planning to make a change that'll cause it).
- [ ] 429/503 handling: There's some prior art from the CI retry-handler, but we probably need to think it through a bit more to propagate useful errors to end-users.

**Comment by olivierproffit** [comment]
Closing as it's outdated and we are using partially U2C instead of WDM
