### ISSUE TITLE
Pipeline V5

### ISSUE THREAD

**Issue by ianwremmel** [webex/webex-js-sdk#76]
# Phase 1
- [x] merge
- [ ] Publish to CDN
- [ ] Add pusher to build description
# Phase 2
- [ ] Replace propagate:false with try/catch
- [ ] Switch gating jobs to invoke groovy script/remove gate.sh
- [ ] Publish to GHE
# Phase 3
- [ ] Check build log for disconnect/reconnect
- [ ] Wrap all stages in an abort check
- [ ] Propagate aborts to containers (blocked on Jenkins update, hopefully to be done 2/4)
- [ ] Investigate Docker Compose
- [ ] Update docs
